# Generated by Django 5.0.3 on 2024-03-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='members',
        ),
    ]
